---
#

- name: Copy hosts file
  copy:
    src: hosts
    dest: /etc/hosts
    backup: yes

- name: Install Packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - bash-completion
    - vim 
    - lsof

- name: Update OS
  yum:
    name: '*'
    state: latest

